site_name: mtcli-atr
repo_url: https://github.com/vfranca/mtcli-atr
repo_name: vfranca/mtcli-atr

theme:
  name: readthedocs
  locale: pt_BR

nav:
  - Início: index.md
  - Contribuindo: contribuindo.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  # - def_list
  # - pymdownx.extra
  # - pymdownx.highlight
  # - pymdownx.superfences
