[project]
name = "mtcli-atr"
version = "0.1.0"
description = "Plugin mtcli do indicador ATR"
authors = [
    {name = "Valmir França da Silva",email = "vfranca3@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14.0"
dependencies = [
    "mtcli (>=1.19.3,<2.0.0)"
]

[project.entry-points."mtcli.plugins"]
atr = "mtcli_atr.atr:atr"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
black = "^25.1.0"

